project_id = "qtzlturyendzmirvbofu"

[functions.send-status-notification]
verify_jwt = false

[functions.send-contact-message]
verify_jwt = false

[functions.chat]
verify_jwt = true

[functions.send-newsletter-email]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = true

[functions.send-registration-notification]
verify_jwt = false

[functions.process-order]
verify_jwt = true

[functions.knack-proxy]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = true

[functions.verify-bank-account]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false
